// segundo semestre/ambientes de desenv de software/UNIFOR-AMB-DES-SOFTWARE-main/UNIFOR-AMB-DES-SOFTWARE-main/02-React/src/components/ContactList.js
import React from 'react';
import Contact from './Contact';

const ContactList = () => {
  const contacts = [
    { id: 1, name: 'John Doe', email: 'john@example.com', phone: '123-456-7890' },
    { id: 2, name: 'Jane Smith', email: 'jane@example.com', phone: '098-765-4321' },
    { id: 3, name: 'Bob Johnson', email: 'bob@example.com', phone: '111-222-3333' },
  ];

  return (
    <div>
      <h2>Contact List</h2>
      {contacts.map((contact) => (
        <Contact
          key={contact.id}
          name={contact.name}
          email={contact.email}
          phone={contact.phone}
        />
      ))}
    </div>
  );
};

export default ContactList;

// UNIFOR-AMB-DES-SOFTWARE-main/UNIFOR-AMB-DES-SOFTWARE-main/03-Angular/src/app/contact-list/contact-list.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ContactComponent } from '../contact/contact.component';

@Component({
  selector: 'app-contact-list',
  standalone: true,
  imports: [CommonModule, ContactComponent],
  templateUrl: './contact-list.component.html',
  styleUrls: ['./contact-list.component.css']
})
export class ContactListComponent {
  contacts = [
    { id: 1, name: 'John Doe', email: 'john@example.com', phone: '123-456-7890' },
    { id: 2, name: 'Jane Smith', email: 'jane@example.com', phone: '098-765-4321' },
    { id: 3, name: 'Bob Johnson', email: 'bob@example.com', phone: '111-222-3333' },
  ];
}
